### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by dusansimic** [DedaDev/jmbg#1]
Hi! First of all, I'd like to say this is a really cool and useful library with rare feature set. To be completely honest, I didn't know all of that data was actually packed inside the JMBG 😁.

Now I have a few ideas on how to refactore the code a bit. I can see there a lot of unnecessary `else` statements since `return` statements are called. For example here:
```javascript
37 if(controlNmb !== Number(jmbg.charAt(jmbg.length-1))) return false
38 else {
```

Also `generate()` function has a bit misleading name. Word generate suggests that an input is supplied and an output is generated based on that input. I think that in this context, word `random` is more appropriate.

And finally, I think it's better to use `throw` statements to emit errors instead of returning a property inside an object. Meaning, `decode()` function would return only the data object or throw an error which could be caught using `try catch` statement.

I'm happy to open a PR if you're interested in implementing these changes 😁.

**Comment by DedaDev** [comment]
Go ahead :)
